# 1. トラックボール（MX8650）を動かすための必須設定
CONFIG_ZMK_MOUSE=y
CONFIG_INPUT=y
CONFIG_SENSOR_MX8650=y

# 2. NFCピン（P0.09 / P0.10）を通常のGPIOとして使う設定
CONFIG_NFCT_PINS_AS_GPIOS=y

# 3. BMP Boostの内部システムと衝突する機能を完全にオフにする（エラー修正）
CONFIG_ZMK_USB_LOGGING=n
CONFIG_USB_DEVICE_STACK=n
CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=n

# 4. リセットピン（BOOT）のGPIO化を防ぎ、物理スイッチを有効化する
CONFIG_GPIO_AS_PINRESET=y

# 親機が子機からのセンサーイベント（回転）を受信してキーマップ変換するための設定
CONFIG_ZMK_KEYMAP_SENSORS=y

# EC11ロータリーエンコーダのドライバーを有効化
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 名前を統一
CONFIG_ZMK_KEYBOARD_NAME="clearorange"
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
