name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      build_args: >
        -DSHIELD=clear_orange_left -DBOARD=nice_nano_v2
        -DSHIELD=clear_orange_right -DBOARD=nice_nano_v2
